[theme]
primaryColor="#3498DB"           # Azul corporativo
backgroundColor="#ECF0F1"        # Fondo muy claro
secondaryBackgroundColor="#FFFFFF"  # Fondo de tarjetas
textColor="#34495E"             # Gris oscuro para texto principal
font="sans serif"

[server]
maxUploadSize=10