# Configuración para AWS Cognito
[cognito]
client_id = "1q0bia6lgvi383r5kpr30pcgft"      # Client ID (proporcionado por tus compañeros)
client_secret = "t4mc6ri76i66v7bod6deci1v6759til10nl0qncaulkor4iqutp"  # Client Secret (proporcionado por tus compañeros)
scope = "poc-smv-genai-api/write poc-smv-genai-api/read"  # Scope requerido según la imagen

# Configuración para API Gateway
[api]
# URL para obtener token (POST GetToken)
auth_url = "https://poc-smv-genai-api-442431377530-us-east-1.auth.us-east-1.amazoncognito.com/oauth2/token"

# URL para obtener documentos (GET GetDocuments)
documents_url = "https://70j7y69yq5.execute-api.us-east-1.amazonaws.com/dev/documents"

# URL para generar análisis (POST Generate)
generate_url = "https://70j7y69yq5.execute-api.us-east-1.amazonaws.com/dev/generate"

# Configuración adicional
timeout_seconds = 30